name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, reopened]

jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    # Permissions needed for labelling Pull Requests automatically
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      continue-on-error: false
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/label-globs.yml"
        sync-labels: true
